spring:
  application:
    name: employee-management

  profiles:
    active: dev

  cache:
    cache-names: employeeCount
    caffeine:
      spec: expireAfterWrite=1m

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"